// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIhXD0zare_ZkMfLs85OlfmwmsM-hhe4I',
    appId: '1:795722542563:web:7056af347a9c7d6fe804d6',
    messagingSenderId: '795722542563',
    projectId: 'fruit-market-78ad0',
    authDomain: 'fruit-market-78ad0.firebaseapp.com',
    storageBucket: 'fruit-market-78ad0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkii49sIzbOg3EI16xHHJwGAYRcMvkTBU',
    appId: '1:795722542563:android:29739bc68fad7ad4e804d6',
    messagingSenderId: '795722542563',
    projectId: 'fruit-market-78ad0',
    storageBucket: 'fruit-market-78ad0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ__0Qy9mjGs1pMapJnrDp1S4MM2EhtY8',
    appId: '1:795722542563:ios:2e0371f44a2633cee804d6',
    messagingSenderId: '795722542563',
    projectId: 'fruit-market-78ad0',
    storageBucket: 'fruit-market-78ad0.appspot.com',
    iosClientId: '795722542563-3if059ir6ht99s3t70cp6dl1a0d87p4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ__0Qy9mjGs1pMapJnrDp1S4MM2EhtY8',
    appId: '1:795722542563:ios:931e8821710283f2e804d6',
    messagingSenderId: '795722542563',
    projectId: 'fruit-market-78ad0',
    storageBucket: 'fruit-market-78ad0.appspot.com',
    iosClientId: '795722542563-g630q8tiknacc4aev83r0qus0r1on3uc.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitMarket.RunnerTests',
  );
}
